name: build

on:
  push:
    branches: [ $default-branch ]
    paths:
      - '**/*.cs'
  pull_request:
    paths:
      - '**/*.cs'
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    uses: KSPModdingLibs/KSPBuildTools/.github/workflows/build.yml@main
    with:
      dependency-identifiers: ${{ vars.DEPENDENCY_IDENTIFIERS }}